---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
     cloud: ospcloud
    register: instance

  - name: Delete instances
    os_server:
      cloud: ospcloud
      name: " {{ item.name }}"
      state: absent 
    with_items: "{{ instance.openstack_servers }}"   
