- hosts: threetierapp
  gather_facts: true
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 30
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"
        
