- hosts: frontends
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://localhost/index.html"
      return_content: true
    register: webpage
    failed_when:
    - "'Ansible has done its job' not in webpage.content"
    - webpage.status != 200
