---

- name: install {{ service }}
  yum:
    name: "{{ service }}"
    state: latest

- name: enable {{ service }} at boot
  service:
    name: "{{ service }}"
    enabled: yes

- name: configure haproxy to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: start {{ service }}
  service:
    name: "{{ service }}"
    state: restarted

