---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_facts:
     cloud: ospcloud
    register: instance

  - debug: 
     msg: "{{instance.ansible_facts.openstack_servers}}"

  - name: Start instance
    os_server_action:
      action: start
      timeout: 200
      cloud: ospcloud
      server: "{{ item.hostname }}"
    with_items: "{{ instance.ansible_facts.openstack_servers }}"
